name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: yarn --ignore-engines
      - name: Percy Test
        uses: percy/exec-action@v0.3.1
      - name: Run end-to-end tests 
        uses: cypress-io/github-action@v2
        with:
          command: "percy exec -- cypress run --record --tag 'e2e'"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}